### ISSUE TITLE
Add support for reading connection string from environment

### ISSUE THREAD

**Issue by nanounanue** [dssg/tyra#77]
Besides this approach:

https://github.com/dssg/tyra/blob/eedcbe1cdc210499518f6e8d4efae7005a9d8c29/config.py#L21-L25

Could be useful to read those variables from the environment (using  `os.envion.get`). 

So, the use with `docker` will be smoother

**Comment by jtwalsh0** [comment]
config.py should be able to take not just database credentials through environment variables but also the db_schema configuration
