### ISSUE TITLE
Remove unnecessary dependencies in requirements.txt

### ISSUE THREAD

**Issue by nanounanue** [dssg/tyra#83]
For example:

https://github.com/dssg/tyra/blob/eedcbe1cdc210499518f6e8d4efae7005a9d8c29/requirements.txt#L8-L10

Also, are  `pandas` and `testing.postgresql` needed?

And these should be moved to `requirements-dev.txt`

https://github.com/dssg/tyra/blob/eedcbe1cdc210499518f6e8d4efae7005a9d8c29/requirements.txt#L13-L15

**Comment by tweddielin** [comment]
so pandas, numpy, scipy and scikit-learn are actually needed for doing some light-weight computation as well as testing.postgresql used in testing. Functions using those packages will be put in a new utils module in the future. I'll move testing.postgresql to requirements-dev.txt too.
